
export default new Map([
["src/content/projects/esc-iklim-farkindaligi-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fesc-iklim-farkindaligi-2024.mdx&astroContentModuleFlag=true")],
["src/content/projects/erasmus-dijital-yetkinlikler-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Ferasmus-dijital-yetkinlikler-2024.mdx&astroContentModuleFlag=true")],
["src/content/projects/erasmus-kultur-diyalogu-2023.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Ferasmus-kultur-diyalogu-2023.mdx&astroContentModuleFlag=true")],
["src/content/projects/esc-sosyal-inovasyon-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fesc-sosyal-inovasyon-2024.mdx&astroContentModuleFlag=true")],
["src/content/projects/esc-kodlama-atolyesi-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fesc-kodlama-atolyesi-2024.mdx&astroContentModuleFlag=true")],
["src/content/projects/esc-genclik-egitimi-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fesc-genclik-egitimi-2024.mdx&astroContentModuleFlag=true")],
["src/content/projects/erasmus-genclik-liderligi-2023.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Ferasmus-genclik-liderligi-2023.mdx&astroContentModuleFlag=true")],
["src/content/events/erasmus-bilgi-gunleri-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fevents%2Ferasmus-bilgi-gunleri-2024.mdx&astroContentModuleFlag=true")],
["src/content/events/genclik-forumu-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fevents%2Fgenclik-forumu-2024.mdx&astroContentModuleFlag=true")],
["src/content/events/genclik-bulusturma-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fevents%2Fgenclik-bulusturma-2024.mdx&astroContentModuleFlag=true")],
["src/content/events/kodlama-maratonu-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fevents%2Fkodlama-maratonu-2024.mdx&astroContentModuleFlag=true")],
["src/content/events/genclik-festivali-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fevents%2Fgenclik-festivali-2024.mdx&astroContentModuleFlag=true")],
["src/content/events/zeka-oyunlari-kampi-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fevents%2Fzeka-oyunlari-kampi-2024.mdx&astroContentModuleFlag=true")],
["src/content/events/zeka-oyunlari-turnuvasi-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fevents%2Fzeka-oyunlari-turnuvasi-2024.mdx&astroContentModuleFlag=true")],
["src/content/posts/yeni-proje-basvurulari.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fyeni-proje-basvurulari.mdx&astroContentModuleFlag=true")],
["src/content/posts/etkinlik-duyurusu-bahar.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fetkinlik-duyurusu-bahar.mdx&astroContentModuleFlag=true")]]);
		