import fs from 'node:fs';
import path from 'node:path';

/**
 * Automatic "newest added first" ordering for content collections.
 *
 * Times come from src/data/added-times.json, generated by the `prebuild` step
 * (scripts/gen-added.mjs) from git history and committed to the repo. Reading a
 * static JSON here — instead of calling git from inside the Astro build — is
 * what makes ordering reliable on Vercel: git is not dependably reachable from
 * module eval on a shallow/partial clone, but the prebuild script (plain shell,
 * after `git fetch --unshallow`) is, and the committed JSON is the fallback.
 *
 * Keys are `${collection}/${entryId}` (e.g. "stories/anil-asci.mdx"). Missing
 * entries resolve to 0 so callers fall back to a date field / id.
 */

let times: Record<string, number> = {};
try {
  const file = path.join(process.cwd(), 'src/data/added-times.json');
  times = JSON.parse(fs.readFileSync(file, 'utf8'));
} catch {}

/** Time (ms epoch) the entry was first added to the repo, or 0 if unknown. */
export function getEntryAddedTime(collection: string, id: string): number {
  return times[`${collection}/${id}`] ?? 0;
}
